### ISSUE TITLE
`{digest}` should be in Imports

### ISSUE THREAD

**Issue by petrbouchal** [JanCaha/CzechData#30]
This line:
https://github.com/JanCaha/CzechData/blob/f94e24c3f43c7d08c845440a5b7a3b8c5d57076a/R/cache_settings.R#L21
which is executed at build time, makes `{digest}` a hard dependency - it is `Suggest`ed by `{memoise}` but the user of `{CzechData}` has no way to load install `{CzechData}` without also installing `{digest}`.

This logic is not discovered by `{renv}` which causes failures on CI systems such as  Github Actions. If `{digest}` is not installed prior to the installation of `{CzechData}`, the dependency is not available and the installation of `{CzechData}` fails.

This is hard to spot locally, since `{digest}` is almost always installed in a system library, but if you do remove it and try installing `{CzechData}`, it fails:

```
Failed with error:  ‘there is no package called ‘digest’’
Error in memoise::cache_filesystem(cache_path()) : 
  Package `digest` must be installed for `cache_filesystem()`.
Error: unable to load R code in package ‘CzechData’
Execution halted
ERROR: lazy loading failed for package ‘CzechData’
* removing ‘/Users/petr/Library/R/CzechData’
* restoring previous ‘/Users/petr/Library/R/CzechData’

Exited with status 1.
```
...which is what I see on Github Actions.

I am fixing this on a fork, so if you agree with my diagnosis, will submit as a PR.

**Comment by JanCaha** [comment]
Thanks for solving this :)
