### ISSUE TITLE
Reading "adresni mista" layer using `load_ruian_settlement()` fails on some municipalities

### ISSUE THREAD

**Issue by petrbouchal** [JanCaha/CzechData#9]
For example

```
CzechData::load_RUIAN_settlement("547999", "adresni body")

## Error in nchar(x) : invalid multibyte string, element 3
```

This is due to an obscure bug in tidyverse/readr#1136 (or at least I think it's a bug). It can be worked around by explicitly setting the data type for columns in `read_delim()` at

https://github.com/JanCaha/CzechData/blob/d7271b5a467ea28f7459e9b49ceff2b09684c767/R/load_RUIAN.R#L169

(Reading all columns as characters might be OK, or only those starting with "Název".)

Happy to do a PR if you are interested.

**Comment by JanCaha** [comment]
Should be fixed by the latest commit.

**Comment by petrbouchal** [comment]
Excellent, thank you for the speedy fix! Can confirm this now works as expected.
